Nor Gate in NN with  2-binary  inputs

Using Numpy

In [ ]:
import numpy as np

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1],
                   [1, -1]])

weights = [-2, -2]   # weights

bias = 1             #Bias

output = np.dot(inputs, weights) + bias    #basic Neural Structure

sigmoid = 1/(1+np.exp(-output))   #Activation Function (sigmoid)

print(np.round(sigmoid))

[1. 0. 0. 0. 1.]


Nand Gate in NN with 2-binary inputs
using numpy

In [ ]:
import numpy as np

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

weights = [-2, -2]

bias = 3

output = np.dot(inputs, weights) + bias

sigmoid = 1/(1+np.exp(-output))

print(np.round(sigmoid))

[1. 1. 1. 0.]


And Gate in NN with  2-binary  inputs

Using Numpy

In [ ]:
import numpy as np

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

weights = [2, 2]

bias = -3

output = np.dot(inputs, weights) + bias

sigmoid = 1/(1+np.exp(-output))

print(np.round(sigmoid))

[0. 0. 0. 1.]


XOR  Gate in NN with  2-binary  inputs

Using Numpy

In [ ]:
import numpy as np

inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

weights1 = [-2, -2]

weights2 = [2, 2]

bias1 = 1

bias2 = -3

a = np.dot(inputs, weights1) + bias1
a1= np.maximum(0, a)

b = np.dot(inputs, weights2) + bias2
b1 = np.maximum(0, b)

weights3 =[-2, -2]

bias3 = 1

output = a1*weights3[0] +b1*weights3[1] + bias3

relu = np.maximum(0, output)

print(np.round(relu))

[0 1 1 0]


Nor Gate in NN with  3-binary  inputs

Using Numpy


In [ ]:
import numpy as np

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

weights = [-2, -2, -2]

bias = 1

output = np.dot(inputs, weights) + bias

sigmoid = 1/(1+np.exp(-output))

print(np.round(sigmoid))

[1. 0. 0. 0. 0. 0. 0. 0.]


AND Gate in NN with  3-binary  inputs

Using Numpy


In [ ]:
import numpy as np

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

weights = [2, 2, 2]

bias = -5

output = np.dot(inputs, weights) + bias

sigmoid = 1/(1+np.exp(-output))

print(np.round(sigmoid))

[0. 0. 0. 0. 0. 0. 0. 1.]


Nand Gate in NN with 3-binary inputs
Using Numpy

In [ ]:
import numpy as np

inputs = np.array([[0, 0, 0],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 1],
                   [1, 0, 0],
                   [1, 0, 1],
                   [1, 1, 0],
                   [1, 1, 1]])

weights = [-2, -2, -2]

bias = 5

output = np.dot(inputs, weights) + bias

sigmoid = 1/(1+np.exp(-output))

print(np.round(sigmoid))

[1. 1. 1. 1. 1. 1. 1. 0.]


XOR Gate in NN with  3-binary  inputs

Using Numpy



In [ ]:
import numpy as np

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Neural Network class
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases for the hidden layer and output layer
        self.weights_input_hidden = np.random.rand(self.input_size, self.hidden_size)
        self.bias_hidden = np.random.rand(self.hidden_size)
        self.weights_hidden_output = np.random.rand(self.hidden_size, self.output_size)
        self.bias_output = np.random.rand(self.output_size)

    def forward_propagation(self, X):
        # Calculate the output of the hidden layer
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        hidden_output = sigmoid(hidden_input)

        # Calculate the output of the output layer
        output_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output
        output = sigmoid(output_input)

        return output

    def train(self, X, y, epochs):
        for epoch in range(epochs):
            # Forward propagation
            hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
            hidden_output = sigmoid(hidden_input)

            output_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output
            output = sigmoid(output_input)

            # Calculate the error
            error = y - output

            # Backpropagation
            output_delta = error * sigmoid_derivative(output)
            hidden_error = output_delta.dot(self.weights_hidden_output.T)
            hidden_delta = hidden_error * sigmoid_derivative(hidden_output)

            # Update weights and biases
            self.weights_hidden_output += hidden_output.T.dot(output_delta)
            self.bias_output += np.sum(output_delta, axis=0)
            self.weights_input_hidden += X.T.dot(hidden_delta)
            self.bias_hidden += np.sum(hidden_delta, axis=0)


# Create the neural network with 3 input neurons, 4 hidden neurons, and 1 output neuron
nn = NeuralNetwork(input_size=3, hidden_size=4, output_size=1)

# Sample input data (you can replace this with your own data)
X = np.array([[0, 0, 0],
              [0, 0, 1],
              [0, 1, 0],
              [0, 1, 1],
              [1, 0, 0],
              [1, 0, 1],
              [1, 1, 0],
              [1, 1, 1]])

# Sample output data
y = np.array([[0],
              [1],
              [1],
              [0],
              [1],
              [0],
              [0],
              [1]])

# Train the neural network
nn.train(X, y, epochs=10000, verbose=1)

# Test the neural network with new data
new_data = np.array([[0, 1, 0]])
predicted_output = nn.forward_propagation(new_data)
print("Predicted Output:", np.round(predicted_output))


Predicted Output: [[1.]]
